### ISSUE TITLE
筛选标签后没有刷新分数

### ISSUE THREAD

**Issue by EndlessCheng** [karentwan/LeetCodeAssistant#2]
见 https://www.bilibili.com/video/BV1mG411V7fj?t=37m26s

**Comment by karentwan** [comment]
这个问题我也发现了，主要出现在第一次使用标签筛选题目的时候分数不会更新，原因就在于，我监听的是第一行节点的变化
![image](https://user-images.githubusercontent.com/13724818/187102882-6b6cbd9e-fb3a-4891-afed-bd651737d53e.png)
而第一次使用标签筛选题目的时候第一行节点不会变化，仍然还是每日一题（只有切换了页码之后每日一题那里才会消失），所以第一次使用标签筛选不会触发分数的更新，只有切换一次页码后，分数更新就正常了。
后面想想办法解决一下这个bug。

**Comment by karentwan** [comment]
根据标签筛选题目第一次不会刷新分数的bug已经修复了，通过增加head监听触发分数更新可以解决这个bug.
![image](https://user-images.githubusercontent.com/13724818/187202048-f6bff575-23eb-4ee5-9f6c-b1b8911649f5.png)
