### ISSUE TITLE
使用过程有问题，插件报错了

### ISSUE THREAD

**Issue by outstandingzxy** [karentwan/LeetCodeAssistant#7]
遇到的问题 ， 配置之后，插件报错了，没有得到预期的效果

lc页面和之前一样

（不知道是不是我操作有问题..）

报错提示 ， 在init() 函数中的问题
`Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.`

![image](https://user-images.githubusercontent.com/72517823/188487551-01b80df5-773a-4d4e-9245-7ea62bfcc562.png)

**Comment by karentwan** [comment]
请问一下，没有达到预期的结果是两个功能都没有生效吗？还是说收藏的随机一题生效了，但是分数的没生效？

**Comment by outstandingzxy** [comment]
> 现在已经好了，两个功能都生效了，能随机也有分数。报错还在，但是似乎没有任何影响

**Comment by karentwan** [comment]
似乎是因为chrome的误报，不影响使用。MutationObserver的observe()方法的一个特点就是只能应用在原生节点上而不能使用在JQuery的节点上，可能是因为代码里面使用了JQuery的缘故触发的误报，不过我已经将JQuery的节点转为了原生节点，所以使用过程是没有问题的，虽然我也不知道它为啥还是提醒这个问题，最终不影响使用就好。没什么问题的话我就把这个issue关掉了哦，祝刷题愉快！

**Comment by outstandingzxy** [comment]
> 

嗯嗯，没问题的，感谢大佬，respect
